### ISSUE TITLE
[✨ Feature Request]: to_logic_form() and edge_attr

### ISSUE THREAD

**Issue by borisrakovan** [LukasZahradnik/PyNeuraLogic#24]
### Is your feature request related to a problem? Please describe.

The `to_logic_form()` method defined [here](https://github.com/LukasZahradnik/PyNeuraLogic/blob/master/neuralogic/core/dataset.py) doesn't seem to consider the 'edge_attr' attribute.

### Describe the solution you'd like

Should't it initialize the edge predicate weights with the values passed to edge_attr? Something in the lines of 

```
Relation.get(edge_name)(int(u), int(v), int(w))[1].fixed() for u, v, w in zip(self.edge_index[0], self.edge_index[1], self.edge_attr[:, 0])
```

**Comment by LukasZahradnik** [comment]
Hi, thanks for the feature request.

I added support for `edge_attr` in the latest version of PyNeuraLogic (`neuralogic==0.1.1`).

[Here](https://github.com/LukasZahradnik/PyNeuraLogic/blob/master/tests/test_datasets.py#L166), you can check basic usage (and how features are encoded) in torch, NumPy, and native python tests.
