### ISSUE TITLE
[🐛 Bug Report]: AttributeError when testing the model

### ISSUE THREAD

**Issue by borisrakovan** [LukasZahradnik/PyNeuraLogic#28]
### Describe the bug

I am trying to test a model using `evaluator.test(test_dataset)`, but I am getting the following exception:

```
[<ipython-input-58-4d4659b17081>](https://localhost:8080/#) in test(test_dataset)
      2 def test(test_dataset: Dataset) -> float:
      3     correct = 0
----> 4     for y, y_hat in evaluator.test(test_dataset):
      5         # print(f"Expected: {y}, Predicted: {round(y_hat)} ({y_hat})")
      6         if round(y) == round(y_hat):

[/usr/local/lib/python3.7/dist-packages/neuralogic/nn/evaluators/java.py](https://localhost:8080/#) in _test()
     62             for sample in dataset.samples:
     63                 result = self.neuralogic_model(sample, False)
---> 64                 yield result.target(), result.output()
     65 
     66         if generator:

[/usr/local/lib/python3.7/dist-packages/neuralogic/nn/java.py](https://localhost:8080/#) in target(self)
     24 
     25     def target(self) -> float:
---> 26         return self.loss.getTarget().value
     27 
     28 

AttributeError: 'cz.cvut.fel.ida.algebra.values.VectorValue' object has no attribute 'value'
```

### Steps to reproduce the behavior

I have my dataset and template set up as discussed in [our recent discussion](https://github.com/LukasZahradnik/PyNeuraLogic/discussions/27) (I am using onehot encoding for the class labels). I am also using  the following settings

```python
settings = Settings(optimizer=Optimizer.ADAM, epochs=n_epochs, learning_rate=0.001, error_function=ErrorFunction.CROSSENTROPY)
```

I am able to successfully run the training loop, but as soon as I want to test the model I receive the AttributeError exception.

### Expected behavior

I should be able to test the model without an error.

### Environment

Google Colab

**Comment by LukasZahradnik** [comment]
Hi, thank you for the bug report. 

It is definitely a bug, and I'm going to take a look at it. Until it is fixed, you can replace
```py
for y, y_hat in evaluator.test(test_dataset):
```
with
```py
for y, y_hat in evaluator.test(test_dataset, generator=False):
```
And it should work as expected. The only difference is that the `test` method will evaluate all samples first and return a list of results instead of evaluating lazily and returning a generator.

**Comment by LukasZahradnik** [comment]
Hello, this issue has been solved in the latest release.
Thanks for the bug report.
