### ISSUE TITLE
[✨ Feature Request]: Adding gradients to NeuralSample for visualisation of importance

### ISSUE THREAD

**Issue by erhc** [LukasZahradnik/PyNeuraLogic#62]
### Is your feature request related to a problem? Please describe.

As described in discussion #59, I would like to visualize the importance of the nodes for the infered prediction.

### Describe the solution you'd like

It would be best to have a way to get the node for some defined predicate, and extract the gradients and weights values.

**Comment by LukasZahradnik** [comment]
Hi, this feature has been added in the 0.8.0 version.

Usage:
```
sample = built_dataset[0]
sample.get_nodes(R.abc)[0].gradient
```

**Comment by erhc** [comment]
Thank you for providing this feature! :)
